name: CD
on: [push]
jobs:
  release-unstable:
    # Don't run on any commit that features [skip ci] in the commit message
    if: "! contains(github.event.head_commit.message, '[skip cd]')"
    name: Publish unstable release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # Publish to npm
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
